name: Python application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.12.3
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install kybra

    - name: Run tests
      run: python -m pytest tests

    - name: Build
      run: python src/main.py
